version: '3.8'

services:
  phpCine:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: phpCine
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    environment:
      - DB_CONNECTION=mysql
      - DB_DATABASE=cinedb
    networks:
      - laravel_network

  mysqlCine:
    container_name: mysqlCine
    image: mysql:8.2
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 2005:3306
    networks:
      - laravel_network

  phpmyadminCine:
    container_name: phpmyadminCine
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 2006:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
