
FROM php:8.2.4-apache
RUN a2enmod rewrite
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN composer require laravel/socialite

#Directorio en el que se trabajará dentro del docker
WORKDIR /var/www

#Se copia todo lo de la carpeta actual al directorio /var/www
COPY . .

#Se establece que habrá un script "entrypoint.sh"
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

#Se expone el puerto 8000
EXPOSE 8000

CMD ["php-fpm"]
