FROM php:8.2-fpm

#Instalación de librarías y dependencias.
RUN apt-get update && apt-get install -y \
    libsqlite3-dev \
    libonig-dev \
    libzip-dev \
    unzip \
    && docker-php-ext-install pdo pdo_sqlite

#Directorio en el que se trabajará dentro del docker
WORKDIR /var/www

#Se copia todo lo de la carpeta actual al directorio /var/www
COPY . .

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Se instala composer
RUN composer install 

#Se establece que habrá un script "entrypoint.sh"
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

#Se expone el puerto 8000
EXPOSE 8000

CMD ["php-fpm"]
